name: remote
on:
  push:
    branches:
      - 'main'
    paths:
      - 'poetry.lock'
jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: mishajw/remote@main
        with:
          dockerhub_repo: 'ccs'
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
